[request_definition]
r = sub, obj, act

# if there is NO resource/object
r = sub, act

# if there are MULTIPLE subjects involved
r = sub, sub2, obj, act

# sub   == subject
# obj   == object
# act   == action