[constraint_definition]
# Separation of Duties -- `sod` --
c = sod("finance_requester", "finance_approver")

# Separation of Duties Max -- `sodMax` --
c2 = sodMax(["payroll_view", "payroll_edit", "payroll_approve"], 1)
#   == user can have ONLY 1 -- about -- "payroll_view", "payroll_edit", "payroll_approve"

# Role Cardinality -- `roleMax` --
c3 = roleMax("superadmin", 2)
#   <= 2 users / can have "superadmin" role

# Prerequisite Role -- `rolePre` --
c4 = rolePre("db_admin", "security_trained")
#   if user wants to have "security_trained" role -> need BEFORE "db_admin"